### ISSUE TITLE
Unhandled Exception thrown parsing files

### ISSUE THREAD

**Issue by nurajbihari** [EricZimmerman/LECmd#8]
Here are some exceptions that I'm receiving when parsing files. There seems to be mainly two:
1) Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
2) Unhandled exception. System.OverflowException: Arithmetic operation resulted in an overflow.

This is occurring it both the lecmd and nuget package that was created. The hashes are the files that are causing the exception. eg 0614ed9d8815219f4db92f425062f969b8ea654cf0b2fd08ee5070617bccd430

ERROR: 0614ed9d8815219f4db92f425062f969b8ea654cf0b2fd08ee5070617bccd430,EXCEPTION,"Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'startIndex')	   at System.BitConverter.ToInt32(Byte[] value, Int32 startIndex)	   at Lnk.ShellItems.ShellBag0X1F..ctor(Byte[] rawBytes)	   at Lnk.LnkFile..ctor(Byte[] rawBytes, String sourceFile)

ERROR: 0819d57ea1b8cf3e902965f13c72f093c6a7904d4cb029ed8173561d5e7a94ba,EXCEPTION,"Unhandled exception. System.OverflowException: Arithmetic operation resulted in an overflow.	   at Lnk.LnkFile..ctor(Byte[] rawBytes, String sourceFile)	   at Lnk.Lnk.LoadFile(String lnkFile)

ERROR: 09f85c2901084a4426a4d85f806ae3dbc4034af7a610fece59cff86a6335b4b6,EXCEPTION,"Unhandled exception. System.OverflowException: Arithmetic operation resulted in an overflow.	   at Lnk.LnkFile..ctor(Byte[] rawBytes, String sourceFile)	   at Lnk.Lnk.LoadFile(String lnkFile)

ERROR: 0f94fac61003fdd323a5f3e6433624f95c292bbd96ccde5d6cebe52dfa7e7468,EXCEPTION,"Unhandled exception. System.OverflowException: Arithmetic operation resulted in an overflow.	   at Lnk.ShellItems.ShellBag0X2E.ProcessPropertyViewDefault(Byte[] rawBytes)	   at Lnk.ShellItems.ShellBag0X2E..ctor(Byte[] rawBytes)	   at Lnk.LnkFile..ctor(Byte[] rawBytes, String sourceFile)	   at Lnk.Lnk.LoadFile(String lnkFile)

ERROR: 12e2298e797fbf2f627a208953e7bffa300e695af32038526691c0749c97f1e9,EXCEPTION,"Unhandled exception. System.OverflowException: Arithmetic operation resulted in an overflow.	   at Lnk.ShellItems.ShellBag0X2E.ProcessPropertyViewDefault(Byte[] rawBytes)	   at Lnk.ShellItems.ShellBag0X2E..ctor(Byte[] rawBytes)	   at Lnk.LnkFile..ctor(Byte[] rawBytes, String sourceFile)	   at Lnk.Lnk.LoadFile(String lnkFile)

ERROR: 16abcdcf3568a4d33b65bf3ac069b2a95d36aed213aefc1473e3f4cab4911e97,EXCEPTION,"Unhandled exception. System.Exception: unknown off3bitmask: 0x20	   at Lnk.ShellItems.ShellBag0X1F..ctor(Byte[] rawBytes)	   at Lnk.LnkFile..ctor(Byte[] rawBytes, String sourceFile)	   at Lnk.Lnk.LoadFile(String lnkFile)	  

ERROR: 1f45bc918e4b2bced0d32a1208e2c52777f6c78bc7687d82fc42fdb84a454b6c,EXCEPTION,"Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'startIndex')	   at System.BitConverter.ToInt32(Byte[] value, Int32 startIndex)	   at Lnk.ShellItems.ShellBag0X1F..ctor(Byte[] rawBytes)	   at Lnk.LnkFile..ctor(Byte[] rawBytes, String sourceFile)

ERROR: 21cf0676c098efa8d8eff77c21df1edda3fe2bd3746c49973bc865469e13fb31,EXCEPTION,"Unhandled exception. System.Exception: unknown off3bitmask: 0x10	   at Lnk.ShellItems.ShellBag0X1F..ctor(Byte[] rawBytes)	   at Lnk.LnkFile..ctor(Byte[] rawBytes, String sourceFile)	   at Lnk.Lnk.LoadFile(String lnkFile)	

ERROR: 2671a1b7926c3047067f23487d121379fc581d70a4730f62da9e3d9cb9a5dca4,EXCEPTION,"Unhandled exception. System.Exception: unknown off3bitmask: 0x10	   at Lnk.ShellItems.ShellBag0X1F..ctor(Byte[] rawBytes)	   at Lnk.LnkFile..ctor(Byte[] rawBytes, String sourceFile)

ERROR: 28987f44e46e02c88391e531a9cda3665c30ff717663fe70508944efd6ff96ad,EXCEPTION,"Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'startIndex')	   at System.BitConverter.ToInt32(Byte[] value, Int32 startIndex)	   at Lnk.ShellItems.ShellBag0X1F..ctor(Byte[] rawBytes)	   at Lnk.LnkFile..ctor(Byte[] rawBytes, String sourceFile)

ERROR: 2a96bc1b12d789eb3beb1c2677c2b0f345c8bc2ac9e426c3698c4ab002e3f6dd,EXCEPTION,"Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'startIndex')	   at System.BitConverter.ToInt16(Byte[] value, Int32 startIndex)	   at Lnk.ShellItems.ShellBag0X1F..ctor(Byte[] rawBytes)	   at Lnk.LnkFile..ctor(Byte[] rawBytes, String sourceFile)

ERROR: 2c6725c16971ddfde5b7ace55559ebebe71c339080eec1948b384f9b2876e3f1,EXCEPTION,"Unhandled exception. System.OverflowException: Arithmetic operation resulted in an overflow.	   at Lnk.LnkFile..ctor(Byte[] rawBytes, String sourceFile)	   at Lnk.Lnk.LoadFile(String lnkFile)

ERROR: 2d8d7243706e1dccb3864ae8ed151303a6505e404c57b0928577e66d44fb6c3d,EXCEPTION,"Unhandled exception. System.OverflowException: Arithmetic operation resulted in an overflow.	   at Lnk.ShellItems.ShellBag0X2E.ProcessPropertyViewDefault(Byte[] rawBytes)	   at Lnk.ShellItems.ShellBag0X2E..ctor(Byte[] rawBytes)	   at Lnk.LnkFile..ctor(Byte[] rawBytes, String sourceFile)

ERROR: 2eda822d669c33d9e7f24e65a55741b6afde5fbd1f1723b991055732d7dc4077,EXCEPTION,"Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'startIndex')

**Comment by nurajbihari** [comment]
You can find a few of the files here. The password to the zip archive is "infected".
https://drive.google.com/file/d/1oUxBnqZ3QChLYnr-7XxzXB2HbwZR1hTj/view?usp=sharing
